import { Injectable } from '@angular/core';
import { Feature } from '../data/features-catalog';

export interface SelectedFeature {
  feature: Feature;
  config: Record<string, string>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared helpers always appended to every generated file
// ─────────────────────────────────────────────────────────────────────────────
const SHARED_HELPERS = `
// ─── Shared Helpers ───────────────────────────────────────────────────────────

async function createButton(config) {
  try {
    const btn = await window.zclient.invoke("ui.create", config);
    if (btn.error) throw btn.error;
    return { success: true, data: window.zclient.instance(btn.uid) };
  } catch (e) {
    createLog("createButton", "Failed to create Button", "", "error");
    return { success: false, data: e };
  }
}

async function createModal(config) {
  try {
    const modal = await window.zclient.invoke("ui.create", config);
    return { success: true, data: window.zclient.instance(modal.uid) };
  } catch (e) {
    createLog("createModal", "Failed to create Modal", "", "error");
    return { success: false, data: e };
  }
}

async function createToast(config) {
  try {
    const toast = await window.zclient.invoke("ui.create", config);
    return { success: true, data: window.zclient.instance(toast.uid) };
  } catch (e) {
    createLog("createToast", "Failed to create Toast", "", "error");
    return { success: false, data: e };
  }
}

async function createDialog(config) {
  try {
    const dialog = await window.zclient.invoke("ui.create", config);
    return { success: true, data: window.zclient.instance(dialog.uid) };
  } catch (e) {
    createLog("createDialog", "Failed to create Dialog", "", "error");
    return { success: false, data: e };
  }
}

async function getUserTeams(userUid) {
  const res = await window.zclient.request({
    url: "/user/" + userUid + "/teams",
    type: "GET",
    cors: false,
    contentType: "application/json",
    externalRequest: false,
  });
  return res?.body?.data ?? [];
}

async function getJobDetails(jobUid) {
  const res = await window.zclient.request({
    url: "/jobs/" + jobUid,
    type: "GET",
    cors: false,
    contentType: "application/json",
    externalRequest: false,
  });
  return res?.body?.data;
}

function createLog(fnName, message, page, level, metadata) {
  page     = page     || "";
  level    = level    || "default";
  metadata = metadata || {};
  const entry = {
    level,
    message: "SDK: fn: " + fnName + (page ? " : page: " + page : "") + " - " + message,
    metadata,
  };
  const fn = level === "info"  ? console.info
           : level === "warn"  ? console.warn
           : level === "error" ? console.error
           : console.log;
  fn(JSON.stringify(entry, null, 2));
}

function genUUID() {
  return (Date.now().toString() + Math.random().toString(36).substring(2, 7)).substring(0, 15);
}

function wait(ms) {
  return new Promise(function(resolve) { setTimeout(resolve, ms); });
}
`.trim();

// ─────────────────────────────────────────────────────────────────────────────

@Injectable({ providedIn: 'root' })
export class CodeGeneratorService {

  /** Generates the complete index.js content from a set of selected features + their config. */
  generate(selected: SelectedFeature[]): string {
    if (selected.length === 0) return '';

    const apiConfigBlock   = this.buildApiConfigBlock(selected);
    const globalInitBlock  = this.buildGlobalInitBlock(selected);
    const stateChangeBlock = this.buildStateChangeBlock(selected);
    const featureBodies    = selected.map(sf => sf.feature.codeBlock(sf.config).trim()).join('\n\n');

    const parts: string[] = [];

    // ── Builder identifier header
    const timestamp = new Date().toISOString();
    const featureList = selected.map(sf => `//   - ${sf.feature.label}`).join('\n');
    const meta = JSON.stringify({
      features: selected.map(sf => ({ id: sf.feature.id, config: sf.config }))
    });
    parts.push(
      `// ╔════════════════════════════════════════════════════════════╗\n` +
      `// ║           Generated by Xtra Custom UI Builder             ║\n` +
      `// ╠════════════════════════════════════════════════════════════╣\n` +
      `// ║  Generated : ${timestamp.padEnd(45)}║\n` +
      `// ║  Features  : ${String(selected.length).padEnd(45)}║\n` +
      `// ╚════════════════════════════════════════════════════════════╝\n` +
      `//\n` +
      `// Included features:\n` +
      featureList + '\n' +
      `//\n` +
      `// @builder-meta: ${meta}`
    );

    // ── SDK initialisation
    parts.push(`// Initialize SDK client\nwindow.zclient = window.ZClient.init();`);

    // ── Environment / API config (only if there are URL fields)
    if (apiConfigBlock) {
      parts.push(
        `// === API Configuration ===\nconst API_CONFIG = {\n  live: {\n${apiConfigBlock}  },\n  staging: {},\n};\n\nconst env = "live";`
      );
    }

    // ── App registered + stateChange
    const appRegisteredBody = [
      `  console.log("ZDK app is registered");`,
      globalInitBlock ? globalInitBlock : '',
      `  window.zclient.on("stateChange", async function (stateChangeData) {`,
      `    const { page, id } = stateChangeData;`,
      stateChangeBlock
        ? stateChangeBlock.split('\n').map(l => '    ' + l).join('\n')
        : '    // No page-specific features selected',
      `  });`,
    ].filter(Boolean).join('\n');

    parts.push(
      `// === App Lifecycle ===\nwindow.zclient.on("app.registered", async function () {\n${appRegisteredBody}\n});`
    );

    // ── Feature function definitions
    parts.push(`// === Feature Implementations ===\n${featureBodies}`);

    // ── Shared helpers (always last)
    parts.push(SHARED_HELPERS);

    return parts.join('\n\n') + '\n';
  }

  // ─── Private assembly helpers ──────────────────────────────────────────────

  /**
   * Builds the `live: { key: "url", ... }` block from every URL-type config field
   * across all selected features.
   */
  private buildApiConfigBlock(selected: SelectedFeature[]): string {
    const lines: string[] = [];
    const seen = new Set<string>();
    for (const { feature, config } of selected) {
      for (const field of feature.requiredConfig) {
        if (field.type === 'url' && config[field.key]?.trim() && !seen.has(field.key)) {
          seen.add(field.key);
          lines.push(`    ${field.key}: "${config[field.key].trim()}",`);
        }
      }
    }
    return lines.length ? lines.join('\n') + '\n' : '';
  }

  /**
   * Builds the body of app.registered that calls each feature's init function.
   */
  private buildGlobalInitBlock(selected: SelectedFeature[]): string {
    const lines: string[] = [];
    for (const { feature } of selected) {
      if (feature.initFnName) {
        lines.push(`  await ${feature.initFnName}();`);
      }
    }
    return lines.length ? lines.join('\n') : '';
  }

  /**
   * Builds the if/else-if chain inside the stateChange handler.
   * Groups features by page so multiple features on the same page are called together.
   */
  private buildStateChangeBlock(selected: SelectedFeature[]): string {
    // Preserve insertion order for pages
    const pageMap = new Map<string, string[]>();

    for (const { feature } of selected) {
      if (!feature.fnName) continue;               // global-only features
      for (const page of feature.pages) {
        if (!pageMap.has(page)) pageMap.set(page, []);
        if (!pageMap.get(page)!.includes(feature.fnName)) {
          pageMap.get(page)!.push(feature.fnName);
        }
      }
    }

    if (pageMap.size === 0) return '';

    const clauses: string[] = [];
    let first = true;

    for (const [page, fnNames] of pageMap) {
      const keyword = first ? 'if' : 'else if';
      first = false;
      const calls = fnNames.map(fn => `  await ${fn}(stateChangeData);`).join('\n');
      clauses.push(`${keyword} (page === "${page}") {\n${calls}\n}`);
    }

    return clauses.join(' ');
  }
}
